---
- include_tasks: install.yml
  tags:
    - acme_sh_install

- include_tasks: logging.yml
  tags:
    - acme_sh_logging
  when: acme_sh_logging

- include_tasks: notify.yml
  tags:
    - acme_sh_notify
  when: acme_sh_notify

- include_tasks: manage.yml
  tags:
    - acme_sh_manage
